StartupEvents.registry('item', event => {
	event.create('incomplete_void_mechanism')
	event.create('void_mechanism').glow(true)
	event.create('hydraulic_mechanism')
	event.create('incomplete_hydraulic_mechanism')
	event.create('incomplete_thermal_mechanism')
	event.create('thermal_mechanism')
	event.create('lavender_quartz')
	event.create('polished_lavender_quartz')
	event.create('graphite')
})